services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - WEBPASSWORD=ZAQ!2wsx
      - DNSMASQ_LISTENING=all
      - FTLCONF_LOCAL_IPV4=127.0.0.1
    volumes:
      - './.pihole/etc-pihole:/etc/piehole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8089:80/tcp"

networks:
  piehole-network:
    name: local-network
    external: true